### ISSUE TITLE
headless Chromium instead of Google Chrome (for Javascript support)

### ISSUE THREAD

**Issue by 07416** [damoeb/feedless#14]
https://github.com/damoeb/feedless/blob/master/docs/self-hosting.md#start-all-in-one-image

> Alternatively if you want JavaScript support use the `feedless:aio-chrome` image. This image includes a chrome browser for headless rendering.

Is it possible to provide the more open Chromium as an alternative... or switch to it altogether?

**Comment by damoeb** [comment]
Good catch! I checked the [base image](https://github.com/Zenika/alpine-chrome/blob/master/Dockerfile) for the agent package and the [Dockerfile for the all-in-one image](https://github.com/damoeb/feedless/blob/master/docker-images/with-puppeteer/Dockerfile) and both use chromium. I will resolve the naming confusion.
